In [4]:
from pyspark.sql import SparkSession
from pyspark.sql.types import *
from datetime import datetime

In [5]:
spark=SparkSession.builder \
    .appName("Spark") \
    .enableHiveSupport() \
    .getOrCreate()

In [6]:
spark

In [8]:
schema=StructType([
    StructField("order_id ",StringType(),True),
    StructField("order_item_id ",IntegerType(),True),
    StructField("product_id ",StringType(),True),
    StructField("seller_id",StringType(),True),
    StructField("shipping_limit_date",TimestampType(),True),
    StructField("price",DoubleType(),True),
    StructField("freight_value",DoubleType(),True),
])

path="data/order_items_dataset.csv"
df=spark.read.format('csv').option('header','true').option('inferSchema','false').schema(schema).load(path)

df.printSchema()
df.show(5)

root
 |-- order_id : string (nullable = true)
 |-- order_item_id : integer (nullable = true)
 |-- product_id : string (nullable = true)
 |-- seller_id: string (nullable = true)
 |-- shipping_limit_date: timestamp (nullable = true)
 |-- price: double (nullable = true)
 |-- freight_value: double (nullable = true)

+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date|price|freight_value|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+
|00010242fe8c5a6d1...|             1|4244733e06e7ecb49...|48436dade18ac8b2b...|2017-09-19 09:45:35| 58.9|        13.29|
|00018f77f2f0320c5...|             1|e5f2d52b802189ee6...|dd7ddc04e1b6c2c61...|2017-05-03 11:05:13|239.9|        19.93|
|000229ec398224ef6...|             1|c777355d18b72b67a...|5b51032eddd242adc...|2018-01-18 14:48:30|199.0|        17.87|
|00024acbcdf0a6daa...|             1|7634da152a4610f15...|9d7a1d34a50524090...|2018-08-15 10:10:18|12.99|        12.79|
|00042b26cf59d7ce6...|             1|ac6c3623068f30de0...|df560393f3a51e745...|2017-02-13 13:57:51|199.9|        18.14|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+
only showing top 5 rows

In [7]:
df.rdd.getNumPartitions()

4

In [8]:
df_repartitions=df.repartition(10)

In [10]:
df_repartitions.rdd.getNumPartitions()

10

In [12]:
from pyspark.sql.functions import *

In [9]:
df.select('order_id ').show(5,truncate=False)

+--------------------------------+
|order_id                        |
+--------------------------------+
|00010242fe8c5a6d1ba2dd792cb16214|
|00018f77f2f0320c557190d7a144bdd3|
|000229ec398224ef6ca0657da4fc703e|
|00024acbcdf0a6daa1e931b038114c75|
|00042b26cf59d7ce69dfabb4e55b4fd9|
+--------------------------------+
only showing top 5 rows

In [13]:
df2=df.withColumn("year",year(col("shipping_limit_date"))).withColumn("month",month(col("shipping_limit_date")))
df2.show(5,truncate=False)

+--------------------------------+--------------+--------------------------------+--------------------------------+-------------------+-----+-------------+----+-----+
|order_id                        |order_item_id |product_id                      |seller_id                       |shipping_limit_date|price|freight_value|year|month|
+--------------------------------+--------------+--------------------------------+--------------------------------+-------------------+-----+-------------+----+-----+
|00010242fe8c5a6d1ba2dd792cb16214|1             |4244733e06e7ecb4970a6e2683c13e61|48436dade18ac8b2bce089ec2a041202|2017-09-19 09:45:35|58.9 |13.29        |2017|9    |
|00018f77f2f0320c557190d7a144bdd3|1             |e5f2d52b802189ee658865ca93d83a8f|dd7ddc04e1b6c2c614352b383efe2d36|2017-05-03 11:05:13|239.9|19.93        |2017|5    |
|000229ec398224ef6ca0657da4fc703e|1             |c777355d18b72b67abbeef9df44fd0fd|5b51032eddd242adc84c38acab88f23d|2018-01-18 14:48:30|199.0|17.87        |2018|1    |
|00024acbcdf0a6daa1e931b038114c75|1             |7634da152a4610f1595efa32f14722fc|9d7a1d34a5052409006425275ba1c2b4|2018-08-15 10:10:18|12.99|12.79        |2018|8    |
|00042b26cf59d7ce69dfabb4e55b4fd9|1             |ac6c3623068f30de03045865e4e10089|df560393f3a51e74553ab94004ba5c87|2017-02-13 13:57:51|199.9|18.14        |2017|2    |
+--------------------------------+--------------+--------------------------------+--------------------------------+-------------------+-----+-------------+----+-----+
only showing top 5 rows

In [20]:
order_li=["00010242fe8c5a6d1ba2dd792cb16214","00018f77f2f0320c557190d7a144bdd3"]

df2.filter(col("order_id ").isin(order_li)).show()

+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date|price|freight_value|year|month|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+
|00010242fe8c5a6d1...|             1|4244733e06e7ecb49...|48436dade18ac8b2b...|2017-09-19 09:45:35| 58.9|        13.29|2017|    9|
|00018f77f2f0320c5...|             1|e5f2d52b802189ee6...|dd7ddc04e1b6c2c61...|2017-05-03 11:05:13|239.9|        19.93|2017|    5|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+

In [21]:
df2.drop('month').show(5)

+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date|price|freight_value|year|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+
|00010242fe8c5a6d1...|             1|4244733e06e7ecb49...|48436dade18ac8b2b...|2017-09-19 09:45:35| 58.9|        13.29|2017|
|00018f77f2f0320c5...|             1|e5f2d52b802189ee6...|dd7ddc04e1b6c2c61...|2017-05-03 11:05:13|239.9|        19.93|2017|
|000229ec398224ef6...|             1|c777355d18b72b67a...|5b51032eddd242adc...|2018-01-18 14:48:30|199.0|        17.87|2018|
|00024acbcdf0a6daa...|             1|7634da152a4610f15...|9d7a1d34a50524090...|2018-08-15 10:10:18|12.99|        12.79|2018|
|00042b26cf59d7ce6...|             1|ac6c3623068f30de0...|df560393f3a51e745...|2017-02-13 13:57:51|199.9|        18.14|2017|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+
only showing top 5 rows

In [23]:
df2.dropDuplicates(['order_id ','order_item_id ']).show(10)

+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date|price|freight_value|year|month|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+
|00018f77f2f0320c5...|             1|e5f2d52b802189ee6...|dd7ddc04e1b6c2c61...|2017-05-03 11:05:13|239.9|        19.93|2017|    5|
|0015ebb40fb17286b...|             1|50fd2b788dc166edd...|8b321bb669392f516...|2018-01-18 09:11:24| 21.9|         15.1|2018|    1|
|001dbc16dc51075e9...|             1|777d2e438a1b645f3...|4a3ca9315b744ce9f...|2017-02-01 13:17:57| 69.9|         18.0|2017|    2|
|0028de0ca693a1bb2...|             1|059344baebbeaa42f...|955fee9216a65b617...|2018-08-21 03:35:17|29.99|        15.31|2018|    8|
|002c9def9c9b951b1...|             1|2d9ff06c8870a518f...|00720abe85ba08598...|2018-05-21 17:32:03| 78.0|          8.9|2018|    5|
|002f98c0f7efd4263...|             2|880be32f4db1d9f6e...|fa40cc5b934574b62...|2017-08-10 09:30:15| 44.9|         7.16|2017|    8|
|003822434f91204da...|             2|99e71b776debf2f01...|c54679b1324546259...|2018-06-21 02:30:28| 69.0|        18.58|2018|    6|
|00418a49a685c6bb6...|             1|5e21d5cab5d33e770...|6560211a19b47992c...|2017-10-09 20:50:45| 49.0|         7.78|2017|   10|
|0045e3085f083f0f3...|             1|9545d45c37449ccbc...|431af27f296bc6519...|2017-08-17 07:15:16|116.9|        13.84|2017|    8|
|00482f26707872922...|             1|a9c404971d1a5b1cb...|702835e4b785b67a0...|2017-02-17 16:18:07|  7.6|        10.96|2017|    2|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+
only showing top 10 rows

In [24]:
df2.orderBy(col('price').asc(),col('freight_value').desc()).show(10)

+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date|price|freight_value|year|month|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+
|c5bdd8ef3c0ec4202...|             2|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-07 02:55:22| 0.85|         22.3|2018|    5|
|6e864b3f0ec710311...|             1|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-02 20:30:34| 0.85|        18.23|2018|    5|
|3ee6513ae7ea23bdf...|             1|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-04 03:55:26| 0.85|        18.23|2018|    5|
|8272b63d03f5f79c5...|            19|270516a3f41dc035a...|2709af9587499e95e...|2017-07-21 18:25:23|  1.2|         7.89|2017|    7|
|8272b63d03f5f79c5...|            10|05b515fdc76e888aa...|2709af9587499e95e...|2017-07-21 18:25:23|  1.2|         7.89|2017|    7|
|8272b63d03f5f79c5...|             9|05b515fdc76e888aa...|2709af9587499e95e...|2017-07-21 18:25:23|  1.2|         7.89|2017|    7|
|8272b63d03f5f79c5...|            11|05b515fdc76e888aa...|2709af9587499e95e...|2017-07-21 18:25:23|  1.2|         7.89|2017|    7|
|8272b63d03f5f79c5...|             2|05b515fdc76e888aa...|2709af9587499e95e...|2017-07-21 18:25:23|  1.2|         7.89|2017|    7|
|8272b63d03f5f79c5...|            12|270516a3f41dc035a...|2709af9587499e95e...|2017-07-21 18:25:23|  1.2|         7.89|2017|    7|
|8272b63d03f5f79c5...|             4|05b515fdc76e888aa...|2709af9587499e95e...|2017-07-21 18:25:23|  1.2|         7.89|2017|    7|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+
only showing top 10 rows

In [29]:
df2.groupBy('year','month').agg(count('*'),avg('price'),min('price'),max('price')).orderBy(col('year').asc(),col('month').desc()).show()

+----+-----+--------+------------------+----------+----------+
|year|month|count(1)|        avg(price)|min(price)|max(price)|
+----+-----+--------+------------------+----------+----------+
|2016|   12|       1|              10.9|      10.9|      10.9|
|2016|   10|     365|135.83712328767106|       6.0|    1399.0|
|2016|    9|       4|           48.6175|     44.99|      59.5|
|2017|   12|    7726|116.35011390111136|       4.4|    3124.0|
|2017|   11|    7355|120.10219306593969|      3.85|    2990.0|
|2017|   10|    5189|126.81060512622734|       4.5|   2999.99|
|2017|    9|    4724|130.61941574936384|      2.29|    1798.0|
|2017|    8|    5042|111.08554938516372|       3.9|    2649.0|
|2017|    7|    4116|113.04229834791019|       1.2|   2999.89|
|2017|    6|    3801|123.38885819521138|      3.49|    6499.0|
|2017|    5|    4150|121.84468915662596|       3.5|    4690.0|
|2017|    4|    2364|130.35038917089682|       4.9|    4799.0|
|2017|    3|    2751|124.77011995637947|       4.9|    3999.9|
|2017|    2|    1866|131.82315648445902|       3.9|    6735.0|
|2017|    1|     681|117.65747430249642|       2.9|    1999.0|
|2018|    9|      99|146.48989898989896|       6.9|    2299.0|
|2018|    8|    8815|121.62764605785486|       2.2|    6729.0|
|2018|    7|    6672|121.57255395683337|       3.0|    3089.0|
|2018|    6|    6897|126.24863563868189|       3.5|    4590.0|
|2018|    5|    8765|123.71460924129939|      0.85|    3930.0|
+----+-----+--------+------------------+----------+----------+
only showing top 20 rows

In [30]:

# Working with different partitions
accum=spark.sparkContext.accumulator(0)
df2.foreach(lambda row:accum.add(row['price']))

print(accum.value)

13591643.699999392

In [15]:
df2.withColumn("price_category", when(col('price') >= 100 , "High")
               .when((col('price') < 100) & (col('price')>=50),"Medium")
               .otherwise("Low")).show(5)

+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+--------------+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date|price|freight_value|year|month|price_category|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+--------------+
|00010242fe8c5a6d1...|             1|4244733e06e7ecb49...|48436dade18ac8b2b...|2017-09-19 09:45:35| 58.9|        13.29|2017|    9|        Medium|
|00018f77f2f0320c5...|             1|e5f2d52b802189ee6...|dd7ddc04e1b6c2c61...|2017-05-03 11:05:13|239.9|        19.93|2017|    5|          High|
|000229ec398224ef6...|             1|c777355d18b72b67a...|5b51032eddd242adc...|2018-01-18 14:48:30|199.0|        17.87|2018|    1|          High|
|00024acbcdf0a6daa...|             1|7634da152a4610f15...|9d7a1d34a50524090...|2018-08-15 10:10:18|12.99|        12.79|2018|    8|           Low|
|00042b26cf59d7ce6...|             1|ac6c3623068f30de0...|df560393f3a51e745...|2017-02-13 13:57:51|199.9|        18.14|2017|    2|          High|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+--------------+
only showing top 5 rows

In [16]:
from pyspark.sql.window import Window

In [17]:
windowspec=Window.partitionBy('year').orderBy(col('price').asc())

In [28]:
df3=df2.withColumn("dense_rank",dense_rank().over(windowspec))

In [34]:
df3.show()

+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date|price|freight_value|year|month|dense_rank|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
|3ee6513ae7ea23bdf...|             1|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-04 03:55:26| 0.85|        18.23|2018|    5|         1|
|6e864b3f0ec710311...|             1|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-02 20:30:34| 0.85|        18.23|2018|    5|         1|
|c5bdd8ef3c0ec4202...|             2|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-07 02:55:22| 0.85|         22.3|2018|    5|         1|
|f1d5c2e6867fa93ce...|             1|46fce52cef5caa7cc...|2d2322d8421188677...|2018-08-28 21:30:15|  2.2|         7.39|2018|    8|         2|
|de03f4f4bb610147a...|             1|2e8316b31db34314f...|9d7a1d34a50524090...|2018-02-08 00:55:32| 2.99|        11.85|2018|    2|         3|
|f09e36e258656850b...|             1|44d53f1240d633223...|b64d51f0435e884e8...|2018-07-09 13:31:36|  3.0|        12.79|2018|    7|         4|
|f9ccaff7267fd0cf0...|             1|44d53f1240d633223...|b64d51f0435e884e8...|2018-08-14 14:04:44|  3.0|        15.23|2018|    8|         4|
|7c92284adbec8033d...|             1|29781581fb82fe238...|b64d51f0435e884e8...|2018-07-19 17:05:26| 3.06|        18.23|2018|    7|         5|
|7c92284adbec8033d...|             2|29781581fb82fe238...|b64d51f0435e884e8...|2018-07-19 17:05:26| 3.06|        18.23|2018|    7|         5|
|7c92284adbec8033d...|             3|29781581fb82fe238...|b64d51f0435e884e8...|2018-07-19 17:05:26| 3.06|        18.23|2018|    7|         5|
|37193e64eb9a46b7f...|             1|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-28 01:30:49|  3.5|         7.39|2018|    6|         6|
|95d6357ffe41aa6d2...|             1|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|         6|
|95d6357ffe41aa6d2...|             2|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|         6|
|95d6357ffe41aa6d2...|             3|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|         6|
|95d6357ffe41aa6d2...|             4|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|         6|
|95d6357ffe41aa6d2...|             5|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|         6|
|ac403e440819af185...|             1|f2d80346f1dd6986e...|94b9108d4b637ba65...|2018-02-19 23:27:54| 3.54|         14.1|2018|    2|         7|
|47d11383b93b217d9...|             1|0eeeb45e2f5911fd4...|3d4824f20035949c7...|2018-07-05 01:15:48| 3.85|         7.71|2018|    7|         8|
|43bc72f5380889da9...|             1|fa8485bc54eaad5b2...|5f1dc28029d2c2443...|2018-05-09 03:53:02|  3.9|        18.23|2018|    5|         9|
|43bc72f5380889da9...|             2|fa8485bc54eaad5b2...|5f1dc28029d2c2443...|2018-05-09 03:53:02|  3.9|        18.23|2018|    5|         9|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
only showing top 20 rows

In [39]:
df3.select("year").distinct().show()

+----+
|year|
+----+
|2018|
|2020|
|2016|
|2017|
+----+

In [41]:
df3.filter(df3['year']==2020).show(10)

+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date|price|freight_value|year|month|dense_rank|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
|13bdf405f961a6dee...|             1|96ea060e41bdecc64...|7a241947449cc45db...|2020-02-05 03:30:51|69.99|        14.66|2020|    2|         1|
|9c94a4ea2f7876660...|             1|282b126b2354516c5...|7a241947449cc45db...|2020-02-03 20:23:22|75.99|         14.7|2020|    2|         2|
|c2bb89b5c1dd978d5...|             1|87b92e06b320e803d...|7a241947449cc45db...|2020-04-09 22:35:08|99.99|        61.44|2020|    4|         3|
|c2bb89b5c1dd978d5...|             2|87b92e06b320e803d...|7a241947449cc45db...|2020-04-09 22:35:08|99.99|        61.44|2020|    4|         3|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+

In [42]:
df4=df2.withColumn("dense_rank",rank().over(windowspec))

In [43]:
df4.show(20)

+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date|price|freight_value|year|month|dense_rank|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
|3ee6513ae7ea23bdf...|             1|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-04 03:55:26| 0.85|        18.23|2018|    5|         1|
|6e864b3f0ec710311...|             1|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-02 20:30:34| 0.85|        18.23|2018|    5|         1|
|c5bdd8ef3c0ec4202...|             2|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-07 02:55:22| 0.85|         22.3|2018|    5|         1|
|f1d5c2e6867fa93ce...|             1|46fce52cef5caa7cc...|2d2322d8421188677...|2018-08-28 21:30:15|  2.2|         7.39|2018|    8|         4|
|de03f4f4bb610147a...|             1|2e8316b31db34314f...|9d7a1d34a50524090...|2018-02-08 00:55:32| 2.99|        11.85|2018|    2|         5|
|f09e36e258656850b...|             1|44d53f1240d633223...|b64d51f0435e884e8...|2018-07-09 13:31:36|  3.0|        12.79|2018|    7|         6|
|f9ccaff7267fd0cf0...|             1|44d53f1240d633223...|b64d51f0435e884e8...|2018-08-14 14:04:44|  3.0|        15.23|2018|    8|         6|
|7c92284adbec8033d...|             1|29781581fb82fe238...|b64d51f0435e884e8...|2018-07-19 17:05:26| 3.06|        18.23|2018|    7|         8|
|7c92284adbec8033d...|             2|29781581fb82fe238...|b64d51f0435e884e8...|2018-07-19 17:05:26| 3.06|        18.23|2018|    7|         8|
|7c92284adbec8033d...|             3|29781581fb82fe238...|b64d51f0435e884e8...|2018-07-19 17:05:26| 3.06|        18.23|2018|    7|         8|
|37193e64eb9a46b7f...|             1|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-28 01:30:49|  3.5|         7.39|2018|    6|        11|
|95d6357ffe41aa6d2...|             1|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|        11|
|95d6357ffe41aa6d2...|             2|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|        11|
|95d6357ffe41aa6d2...|             3|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|        11|
|95d6357ffe41aa6d2...|             4|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|        11|
|95d6357ffe41aa6d2...|             5|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|        11|
|ac403e440819af185...|             1|f2d80346f1dd6986e...|94b9108d4b637ba65...|2018-02-19 23:27:54| 3.54|         14.1|2018|    2|        17|
|47d11383b93b217d9...|             1|0eeeb45e2f5911fd4...|3d4824f20035949c7...|2018-07-05 01:15:48| 3.85|         7.71|2018|    7|        18|
|43bc72f5380889da9...|             1|fa8485bc54eaad5b2...|5f1dc28029d2c2443...|2018-05-09 03:53:02|  3.9|        18.23|2018|    5|        19|
|43bc72f5380889da9...|             2|fa8485bc54eaad5b2...|5f1dc28029d2c2443...|2018-05-09 03:53:02|  3.9|        18.23|2018|    5|        19|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
only showing top 20 rows

In [44]:
df5=df2.withColumn("dense_rank",row_number().over(windowspec))

In [45]:
df5.show()

+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date|price|freight_value|year|month|dense_rank|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
|3ee6513ae7ea23bdf...|             1|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-04 03:55:26| 0.85|        18.23|2018|    5|         1|
|6e864b3f0ec710311...|             1|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-02 20:30:34| 0.85|        18.23|2018|    5|         2|
|c5bdd8ef3c0ec4202...|             2|8a3254bee785a526d...|96804ea39d96eb908...|2018-05-07 02:55:22| 0.85|         22.3|2018|    5|         3|
|f1d5c2e6867fa93ce...|             1|46fce52cef5caa7cc...|2d2322d8421188677...|2018-08-28 21:30:15|  2.2|         7.39|2018|    8|         4|
|de03f4f4bb610147a...|             1|2e8316b31db34314f...|9d7a1d34a50524090...|2018-02-08 00:55:32| 2.99|        11.85|2018|    2|         5|
|f09e36e258656850b...|             1|44d53f1240d633223...|b64d51f0435e884e8...|2018-07-09 13:31:36|  3.0|        12.79|2018|    7|         6|
|f9ccaff7267fd0cf0...|             1|44d53f1240d633223...|b64d51f0435e884e8...|2018-08-14 14:04:44|  3.0|        15.23|2018|    8|         7|
|7c92284adbec8033d...|             1|29781581fb82fe238...|b64d51f0435e884e8...|2018-07-19 17:05:26| 3.06|        18.23|2018|    7|         8|
|7c92284adbec8033d...|             2|29781581fb82fe238...|b64d51f0435e884e8...|2018-07-19 17:05:26| 3.06|        18.23|2018|    7|         9|
|7c92284adbec8033d...|             3|29781581fb82fe238...|b64d51f0435e884e8...|2018-07-19 17:05:26| 3.06|        18.23|2018|    7|        10|
|37193e64eb9a46b7f...|             1|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-28 01:30:49|  3.5|         7.39|2018|    6|        11|
|95d6357ffe41aa6d2...|             1|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|        12|
|95d6357ffe41aa6d2...|             2|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|        13|
|95d6357ffe41aa6d2...|             3|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|        14|
|95d6357ffe41aa6d2...|             4|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|        15|
|95d6357ffe41aa6d2...|             5|98224bfc1eaadb3a3...|ce616e1913288884e...|2018-06-12 19:15:14|  3.5|        18.23|2018|    6|        16|
|ac403e440819af185...|             1|f2d80346f1dd6986e...|94b9108d4b637ba65...|2018-02-19 23:27:54| 3.54|         14.1|2018|    2|        17|
|47d11383b93b217d9...|             1|0eeeb45e2f5911fd4...|3d4824f20035949c7...|2018-07-05 01:15:48| 3.85|         7.71|2018|    7|        18|
|43bc72f5380889da9...|             1|fa8485bc54eaad5b2...|5f1dc28029d2c2443...|2018-05-09 03:53:02|  3.9|        18.23|2018|    5|        19|
|43bc72f5380889da9...|             2|fa8485bc54eaad5b2...|5f1dc28029d2c2443...|2018-05-09 03:53:02|  3.9|        18.23|2018|    5|        20|
+--------------------+--------------+--------------------+--------------------+-------------------+-----+-------------+----+-----+----------+
only showing top 20 rows

In [48]:
windowSpec2=Window.partitionBy('year').orderBy(col('shipping_limit_date').asc())
df2.withColumn('running_sum',sum('price').over(windowSpec2)).show()

+--------------------+--------------+--------------------+--------------------+-------------------+------+-------------+----+-----+------------------+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date| price|freight_value|year|month|       running_sum|
+--------------------+--------------+--------------------+--------------------+-------------------+------+-------------+----+-----+------------------+
|b2d1902261f105c5c...|             1|5ed3835ea6f96c77b...|aba1721a889e04dec...|2018-01-01 22:08:31| 139.0|         8.23|2018|    1|             139.0|
|3c8e80909dd1066fd...|             1|4308439e0d80d5fe0...|59fb871bf6f4522a8...|2018-01-01 22:13:24|179.99|         27.8|2018|    1|            318.99|
|f2e5bcbd102cd01f1...|             1|2bb3e85f2a403543f...|76d64c4aca3a7baf2...|2018-01-01 22:27:15| 348.9|       118.06|2018|    1|            667.89|
|2e7080c8c24e4a977...|             1|3bdc89e963c6651b8...|fffd5413c0700ac82...|2018-01-01 22:30:19| 262.5|       115.49|2018|    1|            930.39|
|43ac8d91a0749b176...|             1|8dad29b3b6c42d0b9...|4e922959ae960d389...|2018-01-01 22:36:29| 129.0|        13.92|2018|    1|1059.3899999999999|
|9d3ec17c877b8a749...|             1|5d98f7de3b78c8dd8...|ea8482cd71df3c196...|2018-01-01 22:47:59| 27.99|         15.1|2018|    1|1087.3799999999999|
|23a2b629fd7a428b5...|             1|40c7fdb4c192c7df5...|6560211a19b47992c...|2018-01-01 22:48:20|  39.0|         7.78|2018|    1|1126.3799999999999|
|1413b3c018371e723...|             1|e53e557d5a159f5aa...|88460e8ebdecbfecb...|2018-01-01 23:06:37| 109.9|         12.9|2018|    1|           1236.28|
|7064a07883ee3b4bb...|             1|d272d0921188b0bd9...|8b321bb669392f516...|2018-01-01 23:28:16| 11.55|         7.78|2018|    1|           1247.83|
|a4d8035f68861eb25...|             1|22f49044bc3eaead7...|4a3ca9315b744ce9f...|2018-01-01 23:28:19|  89.9|        12.97|2018|    1|           1337.73|
|30f3a786f4600561b...|             1|25f86162fee18735f...|1a3df491d1c4f1589...|2018-01-01 23:38:21| 149.9|        21.54|2018|    1|           1487.63|
|4918be3d76a428540...|             1|4c2394abfbac7ff59...|cc419e0650a3c5ba7...|2018-01-01 23:46:30| 84.99|        19.13|2018|    1|1572.6200000000001|
|c25b7410c11056133...|             1|fd471a043ee8b8dd2...|77530e9772f57a62c...|2018-01-01 23:48:23| 299.0|        22.58|2018|    1|1871.6200000000001|
|2285d8448d2a9e6ff...|             1|aca2eb7d00ea1a7b8...|955fee9216a65b617...|2018-01-02 00:49:46|  75.0|        13.08|2018|    1|1946.6200000000001|
|4b21051fef724a86e...|             1|817e1c2d22418c363...|624f4ece8da4aafb7...|2018-01-02 01:26:21| 159.0|        37.74|2018|    1|           2165.52|
|4b21051fef724a86e...|             2|a155b4eeffbbec8a7...|77530e9772f57a62c...|2018-01-02 01:26:21|  59.9|         7.55|2018|    1|           2165.52|
|0e577169a545cf287...|             1|1d9263e74c3e8e57d...|dd2bdf855a9172734...|2018-01-02 02:11:14|  39.9|         15.1|2018|    1|           2205.42|
|b4411c4be4f9514e5...|             1|8b75356a402f017bf...|4e922959ae960d389...|2018-01-02 02:12:36| 122.0|        12.35|2018|    1|           2327.42|
|7658a7ef580794d45...|             1|75d6b6963340c6063...|cc419e0650a3c5ba7...|2018-01-02 02:15:30| 56.99|        17.68|2018|    1|           2384.41|
|e4c2e14a7b74c3530...|             1|7bcc0cf24eb0ae336...|7142540dd4c91e223...|2018-01-02 02:16:34|  84.9|        13.61|2018|    1|           2469.31|
+--------------------+--------------+--------------------+--------------------+-------------------+------+-------------+----+-----+------------------+
only showing top 20 rows

In [49]:
seller_df=spark.read.format('csv').option('header','true').option('inferSchema','true').load('data/sellers_dataset.csv')

In [50]:
seller_df.show(5)

+--------------------+----------------------+-----------------+------------+
|           seller_id|seller_zip_code_prefix|      seller_city|seller_state|
+--------------------+----------------------+-----------------+------------+
|3442f8959a84dea7e...|                 13023|         campinas|          SP|
|d1b65fc7debc3361e...|                 13844|       mogi guacu|          SP|
|ce3ad9de960102d06...|                 20031|   rio de janeiro|          RJ|
|c0f3eea2e14555b6f...|                  4195|        sao paulo|          SP|
|51a04a8a6bdcb23de...|                 12914|braganca paulista|          SP|
+--------------------+----------------------+-----------------+------------+
only showing top 5 rows

In [56]:
order_seller_df=df2.join(seller_df,on="seller_id")

In [57]:
order_seller_df.show(10)

+--------------------+--------------------+--------------+--------------------+-------------------+------+-------------+----+-----+----------------------+-------------------+------------+
|           seller_id|           order_id |order_item_id |         product_id |shipping_limit_date| price|freight_value|year|month|seller_zip_code_prefix|        seller_city|seller_state|
+--------------------+--------------------+--------------+--------------------+-------------------+------+-------------+----+-----+----------------------+-------------------+------------+
|48436dade18ac8b2b...|00010242fe8c5a6d1...|             1|4244733e06e7ecb49...|2017-09-19 09:45:35|  58.9|        13.29|2017|    9|                 27277|      volta redonda|          SP|
|dd7ddc04e1b6c2c61...|00018f77f2f0320c5...|             1|e5f2d52b802189ee6...|2017-05-03 11:05:13| 239.9|        19.93|2017|    5|                  3471|          sao paulo|          SP|
|5b51032eddd242adc...|000229ec398224ef6...|             1|c777355d18b72b67a...|2018-01-18 14:48:30| 199.0|        17.87|2018|    1|                 37564|      borda da mata|          MG|
|9d7a1d34a50524090...|00024acbcdf0a6daa...|             1|7634da152a4610f15...|2018-08-15 10:10:18| 12.99|        12.79|2018|    8|                 14403|             franca|          SP|
|df560393f3a51e745...|00042b26cf59d7ce6...|             1|ac6c3623068f30de0...|2017-02-13 13:57:51| 199.9|        18.14|2017|    2|                 87900|             loanda|          PR|
|6426d21aca402a131...|00048cc3ae777c65d...|             1|ef92defde845ab845...|2017-05-23 03:55:27|  21.9|        12.69|2017|    5|                 14091|     ribeirao preto|          SP|
|7040e82f899a04d1b...|00054e8431b9d7675...|             1|8d4f2bb7e93e6710a...|2017-12-14 12:10:31|  19.9|        11.85|2017|   12|                  1026|          sao paulo|          SP|
|5996cddab893a4652...|000576fe39319847c...|             1|557d850972a7d6f79...|2018-07-10 12:30:45| 810.0|        70.75|2018|    7|                 19010|presidente prudente|          SP|
|a416b6a846a117243...|0005a1a1728c9d785...|             1|310ae3c140ff94b03...|2018-03-26 18:31:29|145.95|        11.65|2018|    3|                  3702|          sao paulo|          SP|
|ba143b05f0110f0dc...|0005f50442cb953dc...|             1|4535b0e1091c278df...|2018-07-06 14:10:56| 53.99|         11.4|2018|    7|                  2274|          sao paulo|          SP|
+--------------------+--------------------+--------------+--------------------+-------------------+------+-------------+----+-----+----------------------+-------------------+------------+
only showing top 10 rows

In [68]:
order_seller_df.groupBy('seller_id','seller_state').agg(count('*').alias("total_sales")).orderBy(col("total_sales").desc()).show()

+--------------------+------------+-----------+
|           seller_id|seller_state|total_sales|
+--------------------+------------+-----------+
|6560211a19b47992c...|          SP|       2033|
|4a3ca9315b744ce9f...|          SP|       1987|
|1f50f920176fa81da...|          SP|       1931|
|cc419e0650a3c5ba7...|          SP|       1775|
|da8622b14eb17ae28...|          SP|       1551|
|955fee9216a65b617...|          SP|       1499|
|1025f0e2d44d7041d...|          SP|       1428|
|7c67e1448b00f6e96...|          SP|       1364|
|ea8482cd71df3c196...|          SP|       1203|
|7a67c85e85bb2ce85...|          SP|       1171|
|4869f7a5dfa277a7d...|          SP|       1156|
|3d871de0142ce09b7...|          SP|       1147|
|8b321bb669392f516...|          SP|       1018|
|cca3071e3e9bb7d12...|          SP|        830|
|620c87c171fb2a6dd...|          RJ|        798|
|a1043bafd471dff53...|          MG|        770|
|e9779976487b77c6d...|          SP|        750|
|f8db351d8c4c4c22c...|          SP|        724|
|d2374cbcbb3ca4ab1...|          SP|        631|
|391fc6631aebcf300...|          SP|        613|
+--------------------+------------+-----------+
only showing top 20 rows

## Broadcast Join

In [70]:
result= df2.join(broadcast(seller_df),df2.seller_id==seller_df.seller_id,'inner').drop(seller_df.seller_id)

In [71]:
result.show(10)

+--------------------+--------------+--------------------+--------------------+-------------------+------+-------------+----+-----+----------------------+-------------------+------------+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date| price|freight_value|year|month|seller_zip_code_prefix|        seller_city|seller_state|
+--------------------+--------------+--------------------+--------------------+-------------------+------+-------------+----+-----+----------------------+-------------------+------------+
|00010242fe8c5a6d1...|             1|4244733e06e7ecb49...|48436dade18ac8b2b...|2017-09-19 09:45:35|  58.9|        13.29|2017|    9|                 27277|      volta redonda|          SP|
|00018f77f2f0320c5...|             1|e5f2d52b802189ee6...|dd7ddc04e1b6c2c61...|2017-05-03 11:05:13| 239.9|        19.93|2017|    5|                  3471|          sao paulo|          SP|
|000229ec398224ef6...|             1|c777355d18b72b67a...|5b51032eddd242adc...|2018-01-18 14:48:30| 199.0|        17.87|2018|    1|                 37564|      borda da mata|          MG|
|00024acbcdf0a6daa...|             1|7634da152a4610f15...|9d7a1d34a50524090...|2018-08-15 10:10:18| 12.99|        12.79|2018|    8|                 14403|             franca|          SP|
|00042b26cf59d7ce6...|             1|ac6c3623068f30de0...|df560393f3a51e745...|2017-02-13 13:57:51| 199.9|        18.14|2017|    2|                 87900|             loanda|          PR|
|00048cc3ae777c65d...|             1|ef92defde845ab845...|6426d21aca402a131...|2017-05-23 03:55:27|  21.9|        12.69|2017|    5|                 14091|     ribeirao preto|          SP|
|00054e8431b9d7675...|             1|8d4f2bb7e93e6710a...|7040e82f899a04d1b...|2017-12-14 12:10:31|  19.9|        11.85|2017|   12|                  1026|          sao paulo|          SP|
|000576fe39319847c...|             1|557d850972a7d6f79...|5996cddab893a4652...|2018-07-10 12:30:45| 810.0|        70.75|2018|    7|                 19010|presidente prudente|          SP|
|0005a1a1728c9d785...|             1|310ae3c140ff94b03...|a416b6a846a117243...|2018-03-26 18:31:29|145.95|        11.65|2018|    3|                  3702|          sao paulo|          SP|
|0005f50442cb953dc...|             1|4535b0e1091c278df...|ba143b05f0110f0dc...|2018-07-06 14:10:56| 53.99|         11.4|2018|    7|                  2274|          sao paulo|          SP|
+--------------------+--------------+--------------------+--------------------+-------------------+------+-------------+----+-----+----------------------+-------------------+------------+
only showing top 10 rows

### SQL

In [74]:
df2.createOrReplaceTempView("order")
seller_df.createOrReplaceTempView("seller")

In [75]:
join_df=spark.sql("select * from order inner join seller on order.seller_id == seller.seller_id")

In [77]:
join_df.show()

+--------------------+--------------+--------------------+--------------------+-------------------+------+-------------+----+-----+--------------------+----------------------+--------------------+------------+
|           order_id |order_item_id |         product_id |           seller_id|shipping_limit_date| price|freight_value|year|month|           seller_id|seller_zip_code_prefix|         seller_city|seller_state|
+--------------------+--------------+--------------------+--------------------+-------------------+------+-------------+----+-----+--------------------+----------------------+--------------------+------------+
|00010242fe8c5a6d1...|             1|4244733e06e7ecb49...|48436dade18ac8b2b...|2017-09-19 09:45:35|  58.9|        13.29|2017|    9|48436dade18ac8b2b...|                 27277|       volta redonda|          SP|
|00018f77f2f0320c5...|             1|e5f2d52b802189ee6...|dd7ddc04e1b6c2c61...|2017-05-03 11:05:13| 239.9|        19.93|2017|    5|dd7ddc04e1b6c2c61...|                  3471|           sao paulo|          SP|
|000229ec398224ef6...|             1|c777355d18b72b67a...|5b51032eddd242adc...|2018-01-18 14:48:30| 199.0|        17.87|2018|    1|5b51032eddd242adc...|                 37564|       borda da mata|          MG|
|00024acbcdf0a6daa...|             1|7634da152a4610f15...|9d7a1d34a50524090...|2018-08-15 10:10:18| 12.99|        12.79|2018|    8|9d7a1d34a50524090...|                 14403|              franca|          SP|
|00042b26cf59d7ce6...|             1|ac6c3623068f30de0...|df560393f3a51e745...|2017-02-13 13:57:51| 199.9|        18.14|2017|    2|df560393f3a51e745...|                 87900|              loanda|          PR|
|00048cc3ae777c65d...|             1|ef92defde845ab845...|6426d21aca402a131...|2017-05-23 03:55:27|  21.9|        12.69|2017|    5|6426d21aca402a131...|                 14091|      ribeirao preto|          SP|
|00054e8431b9d7675...|             1|8d4f2bb7e93e6710a...|7040e82f899a04d1b...|2017-12-14 12:10:31|  19.9|        11.85|2017|   12|7040e82f899a04d1b...|                  1026|           sao paulo|          SP|
|000576fe39319847c...|             1|557d850972a7d6f79...|5996cddab893a4652...|2018-07-10 12:30:45| 810.0|        70.75|2018|    7|5996cddab893a4652...|                 19010| presidente prudente|          SP|
|0005a1a1728c9d785...|             1|310ae3c140ff94b03...|a416b6a846a117243...|2018-03-26 18:31:29|145.95|        11.65|2018|    3|a416b6a846a117243...|                  3702|           sao paulo|          SP|
|0005f50442cb953dc...|             1|4535b0e1091c278df...|ba143b05f0110f0dc...|2018-07-06 14:10:56| 53.99|         11.4|2018|    7|ba143b05f0110f0dc...|                  2274|           sao paulo|          SP|
|00061f2a7bc09da83...|             1|d63c1011f49d98b97...|cc419e0650a3c5ba7...|2018-03-29 22:28:09| 59.99|         8.88|2018|    3|cc419e0650a3c5ba7...|                  9015|         santo andre|          SP|
|00063b381e2406b52...|             1|f177554ea93259a5b...|8602a61d680a10a82...|2018-07-31 17:30:39|  45.0|        12.98|2018|    7|8602a61d680a10a82...|                  1001|           sao paulo|          SP|
|0006ec9db01a64e59...|             1|99a4788cb24856965...|4a3ca9315b744ce9f...|2018-07-26 17:24:20|  74.0|        23.32|2018|    7|4a3ca9315b744ce9f...|                 14940|            ibitinga|          SP|
|0008288aa423d2a3f...|             1|368c6c730842d7801...|1f50f920176fa81da...|2018-02-21 02:55:52|  49.9|        13.37|2018|    2|1f50f920176fa81da...|                 15025|sao jose do rio p...|          SP|
|0008288aa423d2a3f...|             2|368c6c730842d7801...|1f50f920176fa81da...|2018-02-21 02:55:52|  49.9|        13.37|2018|    2|1f50f920176fa81da...|                 15025|sao jose do rio p...|          SP|
|0009792311464db53...|             1|8cab8abac59158715...|530ec6109d11eaaf8...|2018-08-17 12:15:10|  99.9|        27.65|2018|    8|530ec6109d11eaaf8...|                 85807|            cascavel|          PR|
|0009c9a17f916a706...|             1|3f27ac8e699df3d30...|fcb5ace8bcc92f757...|2018-05-02 09:31:53| 639.0|        11.34|2018|    5|fcb5ace8bcc92f757...|                  7032|           guarulhos|          SP|
|000aed2e25dbad2f9...|             1|4fa33915031a8cde0...|fe2032dab1a61af87...|2018-05-16 20:57:03| 144.0|         8.77|2018|    5|fe2032dab1a61af87...|                 13030|            campinas|          SP|
|000c3e6612759851c...|             1|b50c950aba0dcead2...|218d46b86c1881d02...|2017-08-21 03:33:13|  99.0|        13.71|2017|    8|218d46b86c1881d02...|                 14070|      ribeirao preto|          SP|
|000e562887b1f2006...|             1|5ed9eaf534f6936b5...|8cbac7e12637ed9cf...|2018-02-28 12:08:37|  25.0|        16.11|2018|    2|8cbac7e12637ed9cf...|                 89254|      jaragua do sul|          SC|
+--------------------+--------------+--------------------+--------------------+-------------------+------+-------------+----+-----+--------------------+----------------------+--------------------+------------+
only showing top 20 rows

In [80]:
order_seller_df.write.format("csv").option('header','true').option('delimiter',',').save('/home/jovyan/work/output/join_csv')
print("Write successully")

Write successully

#### Hive

In [86]:
spark.sql(""" set hive.exec.dynamic.partition.mode=nonstrict""")
spark.sql("CREATE DATABASE IF NOT EXISTS tables_by_spark")
spark.sql("USE tables_by_spark")
spark.sql("""
        CREATE TABLE IF NOT EXISTS order_seller_data(
            order_id STRING,
            product_id STRING,
            price DOUBLE,
            freight_value DOUBLE,
            seller_city STRING
        ) PARTITIONED BY (year INT)
""")

join_df.select('order_id ','product_id ','price','freight_value','seller_city','year').write.mode("append").insertInto("order_seller_data")